### ISSUE TITLE
Kotlin data class boolean properties with "is" prefix are ignored

### ISSUE THREAD

**Issue by moranlefler** [victools/jsonschema-generator#363]
When generating a schema for following Kotlin data class, no definition is created for the `isBool` attribute.
```kotlin
  data class TestIsBoolean(val isBool: Boolean)
```

I suspect that it has to do with some Kotlin-specific naming logic that removes the prefix in compile time.
It's still not clear to me why the attribute is ignored completely rather than defined without the prefix.
Of course, the expected behavior, in this case, would be to have a schema property called `isBool`.

I'll be happy to contribute a fix, but not sure where to start. Any idea what the root cause is and how to approach fixing it?

**Comment by CarstenWickner** [comment]
Hi @moranlefler,

I also suspect Kotlin is too smart here.
Your schema generation is likely using the `OptionPreset.PLAIN_JSON`, right? I.e., only considering fields with a corresponding getter to it.

Perhaps the data class generated by Kotlin doesn't follow the naming convention expected by the schema generator:
- Expected by schema generator: for a field with name `isBool` the getter would be called `isIsBool()` or `getIsBool()`
- What Kotlin generates (just guessing) for a field with name `isBool` the generated getter has the name `isBool()`

To narrow this down I'd suggest you try:
1. Using the `OptionPreset.FULL_DOCUMENTATION`, which also includes `private` fields without a getter method, i.e., this should then include the `isBool` property (and the corresponding getter as well).
2. Check what the schema generator produces for this data class:
```kotlin
data class TestIsBoolean(val bool: Boolean)
```

I'm my guess is right, we could consider extending the `FieldScope.doFindGetter()` method to also check for a method whose name matches the field name exactly:
https://github.com/victools/jsonschema-generator/blob/baea9b68690716a56afea2b5f46474296629a1eb/jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/FieldScope.java#L114-L126
But let's first have a look at the output with `OptionPreset.FULL_DOCUMENTATION`.

**Comment by moranlefler** [comment]
Thanks for your reply @CarstenWickner ,

Here are some additional test runs and their results:

###  Without Jackson Module
```kotline
    @Test
    fun testIsBoolean() {
        val config = SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2020_12, OptionPreset.PLAIN_JSON)
                .build()
        val generator = SchemaGenerator(config)
        val result = generator.generateSchema(TestIsBoolean::class.java)
        print(result)
    }
```

OUTPUT:
```json
{
   "$schema":"https://json-schema.org/draft/2020-12/schema",
   "type":"object",
   "properties":{
      "isBool":{
         "type":"boolean"
      }
   }
}
```

### Without Jackson Module and `OptionPreset.FULL_DOCUMENTATION`
```kotlin
    @Test
    fun testIsBoolean() {
        val config = SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2020_12, OptionPreset.FULL_DOCUMENTATION)
                .build()
        val generator = SchemaGenerator(config)
        val result = generator.generateSchema(TestIsBoolean::class.java)
        print(result)
    }
```

OUTPUT:
```json
{
   "$defs":{
      "TestIsBoolean-nullable":{
         "anyOf":[
            {
               "type":"null"
            },
            {
               "$ref":"#"
            }
         ]
      }
   },
   "type":"object",
   "properties":{
      "isBool":{
         "type":"boolean"
      },
      "component1()":{
         "type":"boolean"
      },
      "copy(boolean)":{
         "$ref":"#/$defs/TestIsBoolean-nullable"
      },
      "equals(Object)":{
         "type":"boolean"
      },
      "hashCode()":{
         "type":"integer"
      },
      "isBool()":{
         "type":"boolean"
      },
      "toString()":{
         "type":[
            "string",
            "null"
         ]
      }
   }
}
```


### With Jackson Module
```kotlin
    @Test
    fun testIsBoolean() {
        val config = SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2020_12, OptionPreset.PLAIN_JSON)
                .with(JacksonModule())
                .build()
        val generator = SchemaGenerator(config)
        val result = generator.generateSchema(TestIsBoolean::class.java)
        print(result)
    }
```
OUPUT:
```json
{
   "$schema":"https://json-schema.org/draft/2020-12/schema",
   "type":"object"
}
```

### With Jackson Module and `OptionPreset.FULL_DOCUMENTATION`

 @Test
    fun testIsBoolean() {
        val config = SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2020_12, OptionPreset.FULL_DOCUMENTATION)
                .with(JacksonModule())
                .build()
        val generator = SchemaGenerator(config)
        val result = generator.generateSchema(TestIsBoolean::class.java)
        print(result)
    }

OUTPUT:
```json
{
   "$defs":{
      "TestIsBoolean-nullable":{
         "anyOf":[
            {
               "type":"null"
            },
            {
               "$ref":"#"
            }
         ]
      }
   },
   "type":"object",
   "properties":{
      "component1()":{
         "type":"boolean"
      },
      "copy(boolean)":{
         "$ref":"#/$defs/TestIsBoolean-nullable"
      },
      "equals(Object)":{
         "type":"boolean"
      },
      "hashCode()":{
         "type":"integer"
      },
      "isBool()":{
         "type":"boolean"
      },
      "toString()":{
         "type":[
            "string",
            "null"
         ]
      }
   }
}
```

### With `Option.INLINE_ALL_SCHEMAS`
(adding this scenario as I need this option for my use case)

```kotlin
@Test
    fun testIsBoolean() {
        val config = SchemaGeneratorConfigBuilder(SchemaVersion.DRAFT_2020_12, OptionPreset.FULL_DOCUMENTATION)
                .with(Option.INLINE_ALL_SCHEMAS)
                .build()
        val generator = SchemaGenerator(config)
        val result = generator.generateSchema(TestIsBoolean::class.java)
        print(result)
    }
```

OUTPUT:
```txt
java.lang.IllegalArgumentException: Option.INLINE_ALL_SCHEMAS cannot be fulfilled due to a circular reference to com.github.victools.jsonschema.module.jackson.KotlinJacksonModuleTest$TestIsBoolean

	at com.github.victools.jsonschema.generator.impl.module.InlineSchemaModule.provideCustomSchemaDefinition(InlineSchemaModule.java:46)
	at com.github.victools.jsonschema.generator.impl.SchemaGeneratorConfigImpl.lambda$getCustomDefinition$1(SchemaGeneratorConfigImpl.java:269)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at com.github.victools.jsonschema.generator.impl.SchemaGeneratorConfigImpl.getCustomDefinition(SchemaGeneratorConfigImpl.java:271)
	at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.traverseGenericType(SchemaGenerationContextImpl.java:299)
	at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.populateMemberSchema(SchemaGenerationContextImpl.java:787)
	at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.createMethodSchema(SchemaGenerationContextImpl.java:730)
	at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.populateMethodSchema(SchemaGenerationContextImpl.java:702)
	at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.generateObjectDefinition(SchemaGenerationContextImpl.java:464)
	at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.addSubtypeReferencesInDefinition(SchemaGenerationContextImpl.java:366)
	at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.traverseGenericType(SchemaGenerationContextImpl.java:339)
	at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.createStandardDefinition(SchemaGenerationContextImpl.java:233)
	at com.github.victools.jsonschema.generator.impl.module.InlineSchemaModule.provideCustomSchemaDefinition(InlineSchemaModule.java:53)
	at com.github.victools.jsonschema.generator.impl.SchemaGeneratorConfigImpl.lambda$getCustomDefinition$1(SchemaGeneratorConfigImpl.java:269)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647)
	at com.github.victools.jsonschema.generator.impl.SchemaGeneratorConfigImpl.getCustomDefinition(SchemaGeneratorConfigImpl.java:271)
	at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.traverseGenericType(SchemaGenerationContextImpl.java:299)
	at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.traverseGenericType(SchemaGenerationContextImpl.java:276)
	at com.github.victools.jsonschema.generator.impl.SchemaGenerationContextImpl.parseType(SchemaGenerationContextImpl.java:97)
	at com.github.victools.jsonschema.generator.SchemaBuilder.createSchemaForSingleType(SchemaBuilder.java:111)
	at com.github.victools.jsonschema.generator.SchemaBuilder.createSingleTypeSchema(SchemaBuilder.java:56)
	at com.github.victools.jsonschema.generator.SchemaGenerator.generateSchema(SchemaGenerator.java:60)
	at com.github.victools.jsonschema.module.jackson.KotlinJacksonModuleTest.testIsBoolean(KotlinJacksonModuleTest.kt:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
```

**Comment by CarstenWickner** [comment]
As suspected: the generated method is not following the normal getter naming convention, which is why it gets ignored by default.

As per my previous comment, we'd have to extent that handling then what is deemed a getter method.

The circular reference error at the bottom is caused by the `copy()` method, which is only included with `OptionPreset.FULL_DOCUMENTATION`, i.e. should be no problem for your actual use case then.

**Comment by moranlefler** [comment]
I can see the argument for either approach; they both make sense...
One question about the PR - the issue was only reproduced when using `JacksonModule`. I expected the PR to touch on that module. Can you explain why we still get the expected behavior when not using `JacksonModule`?

**Comment by CarstenWickner** [comment]
Hi @moranlefler,

I haven't spent time testing this out in particular, but my guess would be a combination of the below:
- In the Kotlin data class, all fields have `public` visibility.
- The `OptionPreset.PLAIN_JSON` does include all ´public` fields by default, even without a corresponding getter method.
- The `JacksonModule` tries to be smart and implicitly lets the `ObjectMapper` (either the default or whatever you provide to the config builder constructor in the beginning) decide which fields would be serialised in a JSON instance:
https://github.com/victools/jsonschema-generator/blob/main/jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonModule.java#L270-L293
Perhaps that excludes `public´ fields without a getter method and no `@JsonProperty` annotation by default.

**Comment by CarstenWickner** [comment]
Release [v4.32.0](https://github.com/victools/jsonschema-generator/releases/tag/v4.32.0) has been published, including the support for `isBoolean` fields with `isBoolean()` getters.
